/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFeedbackWebhookRouteImport } from './routes/api/public/feedback-webhook'

const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackWebhookRoute =
  ApiPublicFeedbackWebhookRouteImport.update({
    id: '/api/public/feedback-webhook',
    path: '/api/public/feedback-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/scorecard': typeof ScorecardRoute
  '/api/public/feedback-webhook': typeof ApiPublicFeedbackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/scorecard': typeof ScorecardRoute
  '/api/public/feedback-webhook': typeof ApiPublicFeedbackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/scorecard': typeof ScorecardRoute
  '/api/public/feedback-webhook': typeof ApiPublicFeedbackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/interview'
    | '/scorecard'
    | '/api/public/feedback-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/interview'
    | '/scorecard'
    | '/api/public/feedback-webhook'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/interview'
    | '/scorecard'
    | '/api/public/feedback-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  InterviewRoute: typeof InterviewRoute
  ScorecardRoute: typeof ScorecardRoute
  ApiPublicFeedbackWebhookRoute: typeof ApiPublicFeedbackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback-webhook': {
      id: '/api/public/feedback-webhook'
      path: '/api/public/feedback-webhook'
      fullPath: '/api/public/feedback-webhook'
      preLoaderRoute: typeof ApiPublicFeedbackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  InterviewRoute: InterviewRoute,
  ScorecardRoute: ScorecardRoute,
  ApiPublicFeedbackWebhookRoute: ApiPublicFeedbackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
